version: "3"
services:
  express:
    restart: "always"
    build: .
    init: true
    volumes:
      - node_modules_volume:/app/node_modules
    network_mode: "host"
    logging:
      driver: json-file
      options:
        max-file: "3"
        max-size: 3m

volumes:
  node_modules_volume:
