version: '3'
services:
  express:
    build: .
    init: true
    ports:
      - '127.0.0.1:22001:22001'
    volumes:
      - node_modules_volume:/app/node_modules
    logging:
      driver: syslog
      options:
        max-file: '3'
        max-size: 3m

volumes:
  node_modules_volume:
